name: .NET

on:
  push:
    branches:
      -master
      -develop
  pull_request:
    branches:
      -master
      -develop

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Build projects
      run: echo "Building..."
